import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Vishnu Muthukumar",
  keywords: [
    "Vishnu Muthukumar",
    "Web Developer",
    "Portfolio",
    "Next.js",
    "React",
    "JavaScript",
    "Frontend Developer",
    "Software Engineer",
    "Web Design",
    "Web Development",
    "UI/UX",
    "Full Stack Developer",
    "Tech Enthusiast",
    "Open Source",
    "Programming",
    "Coding",
    "Software Development",
    "Tech Portfolio",
  ],
  authors: [{ name: "Vishnu Muthukumar", url: "https://vishnumuthukumar.com" }],
  creator: "Vishnu Muthukumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
